## Exercises: Data Manipulation and Analysis

In [1]:
## For each, you'll need to use libraries like Pandas and NumPy.

In [5]:
import pandas as pd
import numpy as np

# Set a random seed for reproducibility
np.random.seed(42)

# Create a date range for 30 days
dates = pd.date_range(start='2024-01-01', periods=30, freq='D')

# Create a DataFrame
data = {
    'Date': np.random.choice(dates, size=100),
    'Product': np.random.choice(['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Webcam'], size=100),
    'Quantity': np.random.randint(1, 10, size=100),
    'Price': np.round(np.random.uniform(20, 1500, size=100), 2),
    'Region': np.random.choice(['North', 'South', 'East', 'West'], size=100)
}
sales_df = pd.DataFrame(data)

# Introduce some missing values and duplicates for cleaning practice
sales_df.loc[sales_df.sample(frac=0.05).index, 'Price'] = np.nan
sales_df = pd.concat([sales_df, sales_df.sample(n=5, random_state=1)]) # Add 5 duplicate rows

print("Original Sales DataFrame Head:")
print(sales_df.head())
print("\nOriginal Sales DataFrame Info:")
sales_df.info()
print("\nOriginal Sales DataFrame Duplicates (first 5):")
print(sales_df[sales_df.duplicated()].head())

Original Sales DataFrame Head:
        Date  Product  Quantity    Price Region
0 2024-01-07    Mouse         8   984.90  North
1 2024-01-20  Monitor         6   351.92  South
2 2024-01-29  Monitor         8  1074.03  North
3 2024-01-15   Laptop         9   371.13  South
4 2024-01-11   Webcam         4   501.59   East

Original Sales DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
Index: 105 entries, 0 to 93
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      105 non-null    datetime64[ns]
 1   Product   105 non-null    object
 2   Quantity  105 non-null    int64
 3   Price     99 non-null     float64
 4   Region    105 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 4.9+ KB

Original Sales DataFrame Duplicates (first 5):
         Date   Product  Quantity    Price Region
80 2024-01-15  Keyboard         6  1237.45  North
84 2024-01-04    Laptop         4  1159.59   West
33 2024-01-22   Monitor         6  1393.91   East
81 2024-01-03     Mouse         8      NaN  North
93 2024-01-04  Keyboard         3  1464.26   West

In [6]:
# --- Data Cleaning ---

print("--- Data Cleaning ---")

# 1. Identify and remove duplicate rows.
initial_rows = sales_df.shape[0]
sales_df.drop_duplicates(inplace=True)
rows_after_duplicates = sales_df.shape[0]
print(f"Removed {initial_rows - rows_after_duplicates} duplicate rows.")
print(f"DataFrame now has {rows_after_duplicates} rows.\n")

# 2. Handle missing 'Price' values.
# Choice: Fill missing 'Price' values with the mean price.
# Explanation: For sales data, dropping rows with missing prices might lead to losing valuable information about other aspects of the transaction (like product, quantity, date). Filling with the mean allows us to retain those records while providing a reasonable estimate for the missing price, assuming the missing data is random and not indicative of a systematic issue.
mean_price = sales_df['Price'].mean()
sales_df['Price'].fillna(mean_price, inplace=True)
print(f"Filled missing 'Price' values with the mean price: ${mean_price:.2f}\n")

# Verify no more missing values in 'Price'
print("Missing values after cleaning (should be 0 for Price):")
print(sales_df.isnull().sum())
print("\n")

# 3. Ensure 'Date' column is of datetime type.
# It was created as datetime, but it's good practice to ensure.
sales_df['Date'] = pd.to_datetime(sales_df['Date'])
print("Ensured 'Date' column is datetime type.")
print(f"Date column dtype: {sales_df['Date'].dtype}\n")

# Check the cleaned DataFrame info
print("Cleaned Sales DataFrame Info:")
sales_df.info()
print("\n" + "-" * 50 + "\n")


# --- Feature Engineering ---

print("--- Feature Engineering ---")

# Create a new column called 'Total_Sales'
sales_df['Total_Sales'] = sales_df['Quantity'] * sales_df['Price']
print("Added 'Total_Sales' column.")
print(sales_df.head())
print("\n" + "-" * 50 + "\n")


# --- Descriptive Statistics ---

print("--- Descriptive Statistics ---")

# 1. Calculate the total sales for each 'Product'.
total_sales_per_product = sales_df.groupby('Product')['Total_Sales'].sum().sort_values(ascending=False)
print("Total Sales for Each Product:")
print(total_sales_per_product)
print("\n")

# 2. Find the average price of 'Laptop' products.
avg_laptop_price = sales_df[sales_df['Product'] == 'Laptop']['Price'].mean()
print(f"Average Price of Laptop products: ${avg_laptop_price:.2f}\n")

# 3. Determine the most profitable region (based on 'Total_Sales').
total_sales_per_region = sales_df.groupby('Region')['Total_Sales'].sum().sort_values(ascending=False)
most_profitable_region = total_sales_per_region.index[0]
max_region_sales = total_sales_per_region.iloc[0]
print("Total Sales for Each Region:")
print(total_sales_per_region)
print(f"\nMost Profitable Region: {most_profitable_region} with total sales of ${max_region_sales:.2f}\n")
print("-" * 50 + "\n")


# --- Time-based Analysis ---

print("--- Time-based Analysis ---")

# 1. Calculate the daily total sales.
daily_total_sales = sales_df.groupby('Date')['Total_Sales'].sum()
print("Daily Total Sales (first 5 days):")
print(daily_total_sales.head())
print("\n")

# 2. Find the day with the highest sales.
day_highest_sales = daily_total_sales.idxmax()
highest_sales_amount = daily_total_sales.max()
print(f"Day with the Highest Sales: {day_highest_sales.strftime('%Y-%m-%d')} with total sales of ${highest_sales_amount:.2f}\n")
print("-" * 50 + "\n")

# Display the first few rows of the final cleaned and engineered DataFrame
print("Final Cleaned and Engineered DataFrame Head:")
print(sales_df.head())

--- Data Cleaning ---
Removed 5 duplicate rows.
DataFrame now has 100 rows.

Filled missing 'Price' values with the mean price: $806.86

Missing values after cleaning (should be 0 for Price):
Date        0
Product     0
Quantity    0
Price       0
Region      0
dtype: int64


Ensured 'Date' column is datetime type.
Date column dtype: datetime64[ns]

Cleaned Sales DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      100 non-null    datetime64[ns]
 1   Product   100 non-null    object
 2   Quantity  100 non-null    int64
 3   Price     100 non-null    float64
 4   Region    100 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 4.7+ KB

--------------------------------------------------

--- Feature Engineering ---
Added 'Total_Sales' column.
        Date  Product  Quantity    Price Region  Total_Sales
0 2024-01-07    Mouse         8   984.90  North      7879.20
1 2024-01-20  Monitor         6   351.92  South      2111.52
2 2024-01-29  Monitor         8  1074.03  North      8592.24
3 2024-01-15   Laptop         9   371.13  South      3340.17
4 2024-01-11   Webcam         4   501.59   East      2006.36

--------------------------------------------------

--- Descriptive Statistics ---
Total Sales for Each Product:
Product
Laptop      83872.644316
Webcam      81911.727263
Monitor     81525.061474
Mouse       68830.567263
Keyboard    65999.250000
Name: Total_Sales, dtype: float64


Average Price of Laptop products: $691.96

Total Sales for Each Region:
Region
South    107348.191579
North    103530.087263
West     102629.690000
East      68631.281474
Name: Total_Sales, dtype: float64

Most Profitable Region: South with total sales of $107348.19

--------------------------------------------------

--- Time-based Analysis ---
Daily Total Sales (first 5 days):
Date
2024-01-01     9618.000000
2024-01-02     3784.430000
2024-01-03    19450.897263
2024-01-04    16604.610105
2024-01-05     7417.760000
Name: Total_Sales, dtype: float64


Day with the Highest Sales: 2024-01-07 with total sales of $31529.92

--------------------------------------------------

Final Cleaned and Engineered DataFrame Head:
        Date  Product  Quantity    Price Region  Total_Sales
0 2024-01-07    Mouse         8   984.90  North      7879.20
1 2024-01-20  Monitor         6   351.92  South      2111.52
2 2024-01-29  Monitor         8  1074.03  North      8592.24
3 2024-01-15   Laptop         9   371.13  South      3340.17
4 2024-01-11   Webcam         4   501.59   East      2006.36

/var/folders/4f/6s4zkngj5jj99q0nw2m8lh5w0000gn/T/ipykernel_43980/1054474955.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  sales_df['Price'].fillna(mean_price, inplace=True)